# Generated by Django 3.1.2 on 2021-02-25 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LabExam', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Properties',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('exam_date', models.DateField()),
                ('exam_name', models.CharField(max_length=100)),
                ('exam_description', models.TextField()),
                ('total_marks', models.FloatField()),
                ('pass_marks', models.FloatField()),
                ('exam_status', models.BooleanField()),
            ],
        ),
        migrations.DeleteModel(
            name='Brand',
        ),
    ]
